name: bodecom
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  flutter_hex_color: ^1.0.2
  carousel_slider: ^2.3.1
  fl_chart: ^0.12.0
  flutter_svg: ^0.19.0
  searchable_dropdown: ^1.1.3
  # slider_button: ^0.6.
  lite_rolling_switch: ^0.1.1
  date_format: ^1.0.9
  custom_navigation_drawer: ^0.0.1
  curved_navigation_bar: ^0.3.4
  lottie: ^0.7.0+1
  fab_circular_menu: ^1.0.0
  animated_splash_screen: ^1.0.1+2
  page_transition: ^1.1.7+2
  animate_do: ^1.7.3
  http: ^0.12.2
  json_serializable: ^3.5.0
  json_annotation: ^3.1.0
  fluttertoast: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          style: italic
    - family: UniversCondensed
      fonts:
        - asset: fonts/UniversCondensed.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

